site_name: Arms In and Out of Australia
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home: index.md
  - Analysis:
    - analysis/overview.md
  - Sources:
    - source/index.md
    - Department of Foreign Affairs and Trade: source/department-of-foreign-affairs-and-trade.md

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption

